#DATA
data_root: /filer/tmp1/yg397/dataset/lits/lits_3d
classes: 3
modality: CT


#MODEL
arch: vtunet
init_model: '/research/cbim/vast/yg397/github/UTNet/initmodel/swin_tiny_patch4_window7_224.pth'
in_chan: 1
patch_size: [4, 4, 4]

#TRAIN
epochs: 400
training_size: [128, 128, 128] # training crop size
start_epoch: 0
num_workers: 2
aug_device: 'cpu'

split_seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0004 #0.001
betas: [0.9, 0.999]
#momentum: 0.9   # momentum of SGD optimizer
weight_decay: 0.05  # weight decay of SGD optimizer
weight: [0.5, 1, 3]
rlt: 1 # relation between CE and Dice loss


scale: [0.3, 0.3, 0.3]  # scale for data augmentation  0.1 0.3 0.3
rotate: [30, 30, 30] # rotation angle for data augmentation 
translate: [0, 0, 0]
gaussian_noise_std: 0.02

print_freq: 5
iter_per_epoch: 500




#VALIDATION
ema: True
ema_alpha: 0.99
val_freq: 10



#INFERENCE
sliding_window: True
window_size: [128, 128, 128]





# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000' # the port number here should be the same as the previous one
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: null
